# Theme settings
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "sunrise" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
include:
  - _pages
plugins:
  - jekyll-include-cache

# Site Settings
title: "Martin Mangler"
subtitle: "Igneous Petrology | Volcanology"
url: "https://martinmangler.github.io"
header:
  nav: main

# Markdwon processing
markdown: kramdown
kramdown:
  input: GFM

# Minimal Mistakes needs this to avoid build errors on GitHub Pages
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

footer:
  links:
    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.com/citations?hl=en&user=3_3CYkMAAAAJ"
      target: "_blank"
    - label: "ResearchGate"
      icon: "fab fa-researchgate"
      url: "https://www.researchgate.net/profile/Martin-Mangler"
      target: "_blank"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://uk.linkedin.com/in/martin-mangler"
      target: "_blank"
    - label: "Twitter"
      icon: "fab fa-x-twitter"
      url: "https://twitter.com/mangler_m"
      target: "_blank"
      
atom_feed:
  hide: true
  


 


