title: Martin Mangler
remote_theme: "mmistakes/minimal-mistakes@4.27.0"

plugins:
  - jekyll-include-cache

# Optional but recommended minimal settings for Minimal Mistakes
markdown: kramdown
kramdown:
  input: GFM

# Minimal Mistakes needs this to avoid build errors on GitHub Pages
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
